---
title: "p8105_mtp_qz2493.Rmd"
author: "Qingyue Zhuo qz2493"
date: "2022-10-22"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(dplyr)
library(readxl)
library(patchwork)
library(gridExtra)
```

###problem 1
####

###import and tidy the dataset
```{r}
total_df = 
  read_excel("dogweights_07may2022.xlsx", skip = 1) %>%
  janitor::clean_names() %>%
  mutate(
    date = as.POSIXlt.numeric(as.numeric(date)*24*60*60, tz = "UTC", origin = "1899-12-30"),
    date = as.character(date),
    date = substr(date, 1, 10)
    ) 

weight_df =
  select(total_df, date:std) %>%
  separate(raisin, into = c("raisin_lbs", "raisin_oz")) %>%
  separate(simone, into = c("simone_lbs", "simone_oz")) %>%
  separate(gagne, into = c("gagne_lbs", "gagne_oz")) %>%
  separate(std, into = c("std_lbs", "std_oz")) %>%
  mutate(
    raisin = as.numeric(raisin_lbs) + (1/16) * as.numeric(raisin_oz),
    simone = as.numeric(simone_lbs) + (1/16) * as.numeric(simone_oz),
    gagne = as.numeric(gagne_lbs) + (1/16) * as.numeric(gagne_oz),
    std = as.numeric(std_lbs) + (1/16) * as.numeric(std_oz)) %>%
  select(date, raisin:std) %>%
  mutate(
    raisin = ifelse(raisin < 10, raisin + 10, raisin),
    std = ifelse(std == 29.6250, 20 + 15.4/15, std)
  )
  
note_df = 
  select(total_df, date, x6) %>%
  rename("note" = "x6") %>%
  drop_na()
```

```{r}
write_csv(weight_df, "weight_data.csv")
write_csv(note_df,"note.csv")
```

###Problem 2
```{r}
weight_data = read_csv("weight_data.csv")
note_data = read_csv("note.csv")
```

```{r}
#the number of distinct date
weight_data %>% 
  select(date)
  distinct 
#the number of date that is non-NA
sum(!is.na(weight_data$date))
```

```{r}
weight_data %>%
  pivot_longer(
    raisin:std,
    names_to = "dog",
    values_to = "weight"
  ) %>%
  arrange(dog) %>%
  group_by(dog) %>%
  summarize(
    total_observations = sum(!is.na(weight)),
    mean = mean(weight,na.rm = TRUE),
    standard_deviation = sd(weight, na.rm = TRUE)
) %>%
  knitr::kable()
```
###Problem 3
```{r}
weight_data_pivot = 
  weight_data %>%
  pivot_longer(
    raisin:std,
    names_to = "dog",
    values_to = "weight"
  )

```

```{r}
plot1 =
  ggplot(weight_data_pivot, aes(x = dog, y = weight, color = dog)) + geom_boxplot()

plot2 = 
  ggplot(weight_data_pivot, aes(x = date, y = weight, color = dog)) + 
  geom_smooth(se = FALSE) 

grid.arrange(plot1, plot2, nrow = 1)
```

